version: "3"

services:
  docusaurus:
    image: ghcr.io/altecsystems/amaterasudocumentation_docusaurus:latest 
    container_name: docusaurus
    ports:
      - '3000:3000'
    networks:
      - inner-network
  